const express = require("express");
const router = express.Router();
const bcrypt = require("bcrypt");
const User = require("../modals/User");
const jwt = require("jsonwebtoken");
const authMiddleware = require("./middlewares/authMiddleware");
const authController = require("../controllers/auth");
router.post("/signup", authController.postSignUp);
router.post("/login", authController.postLogin);
router.get("/isLoggedIn", authMiddleware, authController.getIsLoggedIn);
router.post("/logout", authMiddleware, authController.postLogOut);
module.exports = router;
