const express = require("express");
const router = express.Router();
const { Journal } = require("../modals/journal");
const User = require("../modals/User");
const authMiddleware = require("./middlewares/authMiddleware");
const mongoose = require("mongoose");
const journalController = require("../controllers/journal");
router.get("/", authMiddleware, journalController.getJournals);
router.get("/:journalId", authMiddleware, journalController.getJournalById);
router.post("/", authMiddleware, journalController.postJournals);
router.post("/:journalId/saved", authMiddleware, journalController.postSaved);
module.exports = router;
